### ISSUE TITLE
where is line argument coming from.

### ISSUE THREAD

**Issue by Toure** [rarebreed/commander#1]
https://github.com/rarebreed/commander/blob/17cabacd634f9966318dcd8524ab14a7fe36cdc6/src/main.rs#L29

**Comment by rarebreed** [comment]
That's just like a Haskell Maybe<T> type.  Just like in Haskell where Maybe
can either be None or Just(someVal), rust has the Option type.  The
reader.next() (asynchronously) returns an Option.  Therefore, it could
either be a None or a Some(x).

If it returns something, you can bind the value returned in the Some to
anything you want.  It's just like a Haskell pattern match.  In rust, you
can do `if let` or `while let` instead of `match`.  If reader.next()
returns a Some type, I bound the value to `line`.  If reader.next()
returned a None type, nothing would happen.  The `line` binding is an
arbitrary value.  I could have chosen anything I wanted.  I'm just choosing
some variable to bind what inner value of the Some type is.

https://doc.rust-lang.org/rust-by-example/flow_control/if_let.html

**Comment by Toure** [comment]
Cool, yeah still digging through the language. But it feels a lot like Haskell and I know now it is due to the fact that Rust Lang is built on Haskell's type system :+1:
